name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  get: 4.6.5
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  equatable: ^2.0.2
  dartz: ^0.10.0
  flutter_animated_dialog: ^2.0.1
  awesome_dialog: ^2.2.1
  lottie: ^1.3.0
  dropdown_search: ^3.0.1
  eva_icons_flutter: ^3.0.1
  intl: ^0.17.0
  flutter_switch: ^0.3.2
  appwrite: ^6.0.0
  flutter: 
    sdk: flutter



flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/svg/
    - assets/lottiefiles/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600


